name: Deploy to other free repo current branch on pr
on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: delete current .git
        run: rm -rf .git
      - name: delete workflows
        run: rm -rf .github
      - name: Extract branch name with replaced underscores
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF//[_]/}"
        id: extract_branch
      - name: Push directory to another repository
        uses: wokstym/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'wokstym'
          destination-repository-name: 'kraksimGUI-deploy'
          user-email: grzegorz.poreba.73@gmail.com
          target-branch: ${{ steps.extract_branch.outputs.branch }}
      - name: Comment deploy link
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: running on branch https://kraksim-git-${{ steps.extract_branch.outputs.branch }}-wokstym.vercel.app/
          check_for_duplicate_msg: false